language: julia

os:
  - linux

julia:
  - 0.5

notifications:
  email: false

sudo: false

script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'Pkg.clone(pwd()); Pkg.build("MarketTechnicals"); Pkg.test("MarketTechnicals")'

after_success:
  - julia -e 'Pkg.add("Documenter")'
  - julia -e 'cd(Pkg.dir("MarketTechnicals", "docs")); include("make.jl")'
