language: julia

os:
  - linux

julia:
  - 0.5
  - 0.6

notifications:
  email: false

sudo: false

script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'Pkg.clone(pwd()); Pkg.build("MarketTechnicals"); Pkg.test("MarketTechnicals", coverage=true)'

after_success:
  - julia -e 'Pkg.add("Documenter")'
  - julia -e 'Pkg.add("MarketData")'
  - julia -e 'cd(Pkg.dir("MarketTechnicals", "docs")); include("make.jl")'

  - julia -e 'Pkg.add("Coverage")'
  - julia -e 'cd(Pkg.dir("MarketTechnicals")); using Coverage; Coveralls.submit(Coveralls.process_folder())'
